Repository Jesulayomy/SCHub, pull requests merged in 2024-10, with the labels that each got.

#20 [Hacktoberfest] [API Docs]: Teacher yml files for /apidocs fixed. Closes #19
  api/views/documentation/teachers/delete_teacher.yml
  api/views/documentation/teachers/new_teachers.yml
  api/views/documentation/teachers/teacher.yml
  api/views/documentation/teachers/update_teacher.yml
  api/views/teachers.py
Labels: bug, documentation, hacktoberfest-accepted

#23 [Hacktoberfest] [Formatting]: Added pre-commit and Ruff. Closes #22
  .github/ISSUE_TEMPLATE/issues.md
  .pre-commit-config.yaml
  CHANGELOG.md
  CONTRIBUTING.md
  LICENSE
  README.md
  SECURITY.md
  api/app.py
  api/auths/__init__.py
  api/auths/login.py
  api/views/__init__.py
  api/views/admins.py
  api/views/courses.py
  api/views/department_courses.py
  api/views/departments.py
  api/views/documentation/teachers/new_teachers.yml
  api/views/documentation/teachers/update_teacher.yml
  api/views/index.py
  api/views/students.py
  api/views/teacher_courses.py
  api/views/teachers.py
  assets/TASKS.md
  configurations/environment
  data/generate_dump.py
  models/__init__.py
  models/admin.py
  models/base.py
  models/course.py
  models/department.py
  models/engine/storage.py
  models/person.py
  models/student.py
  models/teacher.py
  schub/src/index.js
  schub/src/styles/admin.css
  schub/src/styles/create.css
  schub/src/styles/home.css
  schub/src/styles/loading.css
  schub/src/styles/login.css
  schub/src/styles/manage.css
  schub/src/styles/table.css
  schub/src/styles/updateform.css
  tests/test_models/test_admin.py
  tests/test_models/test_base.py
  tests/test_models/test_course.py
  tests/test_models/test_department.py
  tests/test_models/test_engine/test_storage.py
  tests/test_models/test_person.py
  tests/test_models/test_student.py
  tests/test_models/test_teacher.py
Labels: hack, automation, formatting, hacktoberfest-accepted

#25 [Fix]: Requirements for pre-commit, readme .venv update
  README.md
  configurations/environment
  configurations/requirements.txt
Labels: quick-fix, priority, hacktoberfest-invalid

#26 [Merge]: Sync hacktoberfest branch with main
  .github/workflows/greetings.yml
Labels: quick-fix, priority, hacktoberfest-invalid

#28 HACKTOBERFEST : Added hover to homepage and login
  schub/src/pages/Home.js
  schub/src/pages/Layout.js
  schub/src/styles/home.css
  schub/src/styles/layout.css
  schub/src/styles/login.css
Labels: hack, ui/ux, hacktoberfest-accepted

#35 [Hacktoberfest] Feat: Automatic Installation Bash Script
  .gitignore
  install_script.sh
  schub/src/pages/Home.js
  schub/src/pages/Layout.js
  schub/src/styles/home.css
  schub/src/styles/layout.css
  schub/src/styles/login.css
Labels: enhancement, assigned, feature, hacktoberfest-accepted

#36 API docs
  SCHub-API-docs/README.md
  SCHub-API-docs/docs/API Description/Admins/Create_a_new_admin.md
  SCHub-API-docs/docs/API Description/Admins/Delete_an_admin.md
  SCHub-API-docs/docs/API Description/Admins/Retrieve_all_admins.md
  SCHub-API-docs/docs/API Description/Admins/Retrieve_an_admin.md
  SCHub-API-docs/docs/API Description/Admins/Update_an_admin.md
  SCHub-API-docs/docs/API Description/Courses/Create_a_new_course.md
  SCHub-API-docs/docs/API Description/Courses/Delete_a_course.md
  SCHub-API-docs/docs/API Description/Courses/Retrieve_a_course.md
  SCHub-API-docs/docs/API Description/Courses/Retrieve_all_courses.md
  SCHub-API-docs/docs/API Description/Courses/Retrieve_the_teacher_for_a_course.md
  SCHub-API-docs/docs/API Description/Courses/Update_a_course.md
  SCHub-API-docs/docs/API Description/Departments/Create_a_new_course_for_a_department.md
  SCHub-API-docs/docs/API Description/Departments/Create_a_new_department.md
  SCHub-API-docs/docs/API Description/Departments/Delete_a_course_from_a_department.md
  SCHub-API-docs/docs/API Description/Departments/Delete_a_department.md
  SCHub-API-docs/docs/API Description/Departments/Retrieve_a_course_within_a_department.md
  SCHub-API-docs/docs/API Description/Departments/Retrieve_a_department.md
  SCHub-API-docs/docs/API Description/Departments/Retrieve_all_departments.md
  SCHub-API-docs/docs/API Description/Departments/Retrieve_courses_for_a_department.md
  SCHub-API-docs/docs/API Description/Departments/Retrieve_students_for_a_department.md
  SCHub-API-docs/docs/API Description/Departments/Update_a_course_within_a_department.md
  SCHub-API-docs/docs/API Description/Departments/Update_a_department.md
  SCHub-API-docs/docs/API Description/Index/Check_API_status.md
  SCHub-API-docs/docs/API Description/Index/Get_API_statistics.md
  SCHub-API-docs/docs/API Description/Students/Create_a_new_student.md
  SCHub-API-docs/docs/API Description/Students/Delete_a_student.md
  SCHub-API-docs/docs/API Description/Students/Retrieve_a_student.md
  SCHub-API-docs/docs/API Description/Students/Retrieve_all_students.md
  SCHub-API-docs/docs/API Description/Students/Retrieve_courses_for_a_student.md
  SCHub-API-docs/docs/API Description/Students/Update_a_student.md
  SCHub-API-docs/docs/API Description/Teachers/Create_a_new_teacher.md
  SCHub-API-docs/docs/API Description/Teachers/Delete_a_teacher.md
  SCHub-API-docs/docs/API Description/Teachers/Retrieve_a_teacher.md
  SCHub-API-docs/docs/API Description/Teachers/Retrieve_all_teachers.md
  SCHub-API-docs/docs/API Description/Teachers/Retrieve_courses_for_a_teacher.md
  SCHub-API-docs/docs/API Description/Teachers/Update_a_teacher.md
  SCHub-API-docs/docs/index.md
  SCHub-API-docs/docs/js/disable_shortcuts.js
  SCHub-API-docs/docs/js/widgetla.js
  SCHub-API-docs/mkdocs.yml
  SCHub-API-docs/requirements.txt
Labels: documentation, assigned, hacktoberfest-accepted
